#include<stdio.h>
#include<stdlib.h>
#include<string.h>

#include "pds.h"
#include "toll_counter.h"

int main(int argc , char *argv[])
{
	char cmd[100];
	char filename[100];
	int toll_id;
	char vehicle_number[30];
	char toll_type[30];
	struct toll_vehicle test_vehicle;
	int io_count;
	while(strcmp(cmd,"exit")){
		scanf("%s",cmd);
		//LOAD loads all the data in the text file generated by script into the current repo
		if(strcmp(cmd,"LOAD")==0){
			int status;
			if(repo_handle.repo_status != PDS_REPO_OPEN){
			status = TOLL_VEHICLE_FAILURE;
			}
			else				
				status = store_toll_vehicles("electronic_city_toll.txt");
			if(status == TOLL_VEHICLE_SUCCESS)
				printf("%s\n","LOAD successful" );
			else
				printf("%s\n","LOAD failed" );

		}

		if(strcmp(cmd,"OPEN")==0){
			scanf("%s",filename);
			int status = pds_open(filename, sizeof(struct toll_vehicle));	
			if(status == TOLL_VEHICLE_SUCCESS){
				printf("%s\n","OPEN successful" );
			}
			else{
				printf("%s\n","OPEN failed" );
			}
		}
		else if(strcmp(cmd,"STORE")==0){
			scanf("%d%s%s",&toll_id,vehicle_number,toll_type);
			test_vehicle.toll_vehicle_id = toll_id;
			strcpy(test_vehicle.vehicle_number,vehicle_number);
			strcpy(test_vehicle.toll_type,toll_type);
			int status = add_toll_vehicle(&test_vehicle);
			if(status == TOLL_VEHICLE_SUCCESS)
				printf("%s\n","STORE successful" );
			else
				printf("%s\n","STORE failed" );
		}	
		else if(strcmp(cmd,"NDX_MODIFY")==0){
			int newtoll_id;
			scanf("%d%d%s%s",&toll_id,&newtoll_id,vehicle_number,toll_type);
			test_vehicle.toll_vehicle_id = newtoll_id;
			strcpy(test_vehicle.vehicle_number,vehicle_number);
			strcpy(test_vehicle.toll_type,toll_type);
			int status = modify_vehicle_by_vehicle_id(toll_id, &test_vehicle);
			if(status == TOLL_VEHICLE_SUCCESS)
				printf("%s\n","NDX_MODIFY successful" );
			else
				printf("%s\n","NDX_MODIFY failed" );

		}
		else if(strcmp(cmd,"NDX_SEARCH")==0){
			scanf("%d",&toll_id);
			int status = search_vehicle_by_vehicle_id(toll_id, &test_vehicle);
			if(status == TOLL_VEHICLE_SUCCESS)
				printf("%s\n","NDX_SEARCH successful" );
			else
				printf("%s\n","NDX_SEARCH failed" );

		}
		else if(strcmp(cmd,"NON_NDX_SEARCH")==0){
			scanf("%s",vehicle_number);
			int status = search_vehicle_by_vehicle_number(vehicle_number, &test_vehicle, &io_count);
			if(status == TOLL_VEHICLE_SUCCESS)
				printf("%s\n","NON_NDX_SEARCH successful" );
			else
				printf("%s\n","NON_NDX_SEARCH failed" );

		}
		else if(strcmp(cmd,"NDX_DELETE")==0){
			scanf("%d",&toll_id);
			int status = delete_vehicle_by_vehicle_id(toll_id);
			if(status == TOLL_VEHICLE_SUCCESS)
				printf("%s\n","NDX_DELETE successful" );
			else
				printf("%s\n","NDX_DELETE failed" );

		}
		else if(strcmp(cmd,"CLOSE")==0){
			int status = pds_close();
			if(status == PDS_SUCCESS)
				printf("%s\n","CLOSE successful" );
			else
				printf("%s\n","CLOSE failed" );
		}
	}		
	return 0;
}